### ISSUE TITLE
Message string post request undefined

### ISSUE THREAD

**Issue by pajamaw** [learn-co-curriculum/node-js-basic-web-server#3]
curl -X POST http://localhost:3000/message -d '{"id":1,"message":"Our first message."}' Using the given post request returns an undefined message given the set items. I'm not quite sure what's the issue, I even tried the solution method and it appears that it still comes up as undefined. the 3rd test doesn't ask for the message string oddly though, just the id. So I'm not sure if this is a known issue or not. My recent commit can be cloned to show the issue. Simply run
 'node run-server.js' then
 curl -X POST http://localhost:3000/message -d "{id:1, message: 'Our first message.'}"
and check the message status
https://github.com/pajamaw/node-js-basic-web-server-g-416/commit/70f2d1e2f8b857d5ff8d9dcab065dfc7bb5f4dd6

**Comment by pletcher** [comment]
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to you ASAP.

**Comment by pletcher** [comment]
This should work:

`curl -X POST -H "content-type: application/json" http://localhost:3000/message -d '{"id":1,"message":"Our first message."}'`

I added instructions to include the `-H` option. Thanks!
